sudo: false

env:
  - GHCVER=7.8.4
  - GHCVER=7.10.1

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4
      - ghc-7.10.1
      - cabal-install-1.22

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - cabal install hspec-discover
  - mkdir -p $HOME/.local/bin
  - (cd $HOME/.local/bin && wget https://s3-ap-southeast-1.amazonaws.com/zalora-public/tinc && chmod +x ./tinc)

install:
  - tinc

script:
  - cabal configure --enable-tests --ghc-options=-Werror --disable-optimization && cabal build && cabal test

cache:
  directories:
    - $HOME/.tinc/cache
