name: tinc
version: 0.1.0
category: Development
license: "BSD3"
author: "Sönke Hahn"
copyright: "Sönke Hahn"
maintainer: "soenke.hahn@zalora.com"
github: haskell-tinc/tinc

extra-source-files:
  - test/resources/*

ghc-options: -Wall

dependencies:
  - base == 4.*
  - base-compat
  - graph-wrapper >= 0.2.5
  - language-dot
  - containers
  - directory
  - filepath
  - filelock
  - process >= 1.2
  - parsec
  - temporary
  - exceptions
  - transformers
  - hpack >= 0.7.0
  - aeson >= 0.10.0
  - bytestring
  - yaml
  - Cabal == 1.22.*
  - gitrev

source-dirs: src

executables:
  tinc:
    main: tinc.hs
    source-dirs: driver

tests:
  spec:
    main: "Spec.hs"
    source-dirs: test
    dependencies:
      - hspec
      - mockery >= 0.3.0
      - shelly
      - HUnit >= 1.3
      - safe
    cpp-options: -DTEST

  acceptance:
    main: "Spec.hs"
    source-dirs:
      - acceptance
      - test
    dependencies:
      - hspec
      - hspec-expectations
      - mockery
      - shelly
      - stringbuilder
